language: python
python:
  - "3.5"

# command to install dependencies
install: "pip install -r web/code/requirements.txt"

# command to run tests
script: nosetests

after_success:
  - bash <(curl -s https://codecov.io/bash)
